name: open_api_forked
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 2.0.1+1
homepage: https://github.com/stablekernel/open-api-dart
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  codable_forked: ^1.0.0

dev_dependencies:
  test: ^1.16.4
